version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: db
    restart: always
    command: mysqld --sql_mode=""
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - mysql-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - mysql-network

  php:
    build: .
    image: php:apache
    restart: always
    volumes:
      - ./php:/var/www/html
    ports:
      - "8001:80"
    networks:
      - mysql-network

networks:
  mysql-network: