version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - mysql-network
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: php
    restart: always
    volumes:
      - ./php:/var/www/html
    ports:
      - "8001:80"
    depends_on:
      - db   # Corrigido para referenciar o serviço 'db'
    networks:
      - mysql-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
  db_data: