FROM php:8.1-apache
LABEL maintainer="Evelllyn Jade"

# Instalação das extensões PHP necessárias
RUN apt-get update && apt-get install -y \
    && docker-php-ext-install pdo pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && a2enmod rewrite

# Configuração do Apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Exposição da porta 80
EXPOSE 80
